### ISSUE TITLE
View Schedule(s) from Mobile App

### ISSUE THREAD

**Issue by kmillervc** [squadcastHQ/squadcast-support#13]
**Is your feature request related to a problem you are facing? Please describe.**
We would like our users to be able to see the current schedule(s) from the mobile app, including if the user is currently active in the schedule

**Describe the ideal solution that could solve this problem for you**
Ideally, there would be a new menu item named schedules which would present the current schedules in Squadcast.  Additionally, it would be nice to show a user if they were on an active schedule within the App.

**What alternatives did you consider?**
None at this time

**Additional Context**
None at this time

**Comment by raghuchinnannan** [comment]
Hey @kmillervc ,

**Comment by raghuchinnannan** [comment]
Hey @kmillervc ,

We have added the functionality to view schedules directly from Mobile app and released the new version today. Make sure to update your app to the latest version and check again.

Please find the resources related to that below:

[Changelog](https://headwayapp.co/squadcast-updates/mobile-app-improvements-version-2-8-37-135781)
[Support documentation](https://support.squadcast.com/docs/using-the-mobile-app)

We will take your feedback to show a user if they were on an active schedule within the App and try to accommodate it in future releases.
