### ISSUE TITLE
Allow updating status of existing incident

### ISSUE THREAD

**Issue by kmillervc** [squadcastHQ/squadcast-support#4]
**Is your feature request related to a problem you are facing? Please describe.**
We would like the ability to update the status of an incident using an API using a unique ID provided to squadcast when creating the incident.  You can only create an incident currently.  We have some case where our incidents are automatically resolved via external processes.

**Describe the ideal solution that could solve this problem for you**
Add or extend existing implementation with an API that will accept the same JSON format as the create API.  The JSON should also accept a unique ID and status field for updating the existing incident.

**What alternatives did you consider?**
The only alternatives are the web UI and mobile application

**Additional Context**
See https://v2.developer.pagerduty.com/docs/trigger-events

**Comment by raghuchinnannan** [comment]
@kmillervc Currently most of our alert source integrations support this feature where they send the same JSON with a unique ID and a resolved status and we Auto-Resolve the incident from our side. We need to implement the same thing with our incident creation API's as well. We will add it to the backlog and will inform you once implemented.
cc @aelango97

**Comment by raghuchinnannan** [comment]
@kmillervc We have launched a new version of our API integration (APIv2), it should satisfy the mentioned issue. 

Please find the below support article for more information:
https://support.squadcast.com/docs/apiv2
