### ISSUE TITLE
Change notification sound on mobile app (iOS)

### ISSUE THREAD

**Issue by kmillervc** [squadcastHQ/squadcast-support#5]
**Is your feature request related to a problem you are facing? Please describe.**
Replace the existing sound for push notifications on iOS with a custom sound to differentiate from other push notifications.  Incidents typically require more attention which may be lost by not providing a unique sound.

**Describe the ideal solution that could solve this problem for you**
Use a unique sound for the mobile app on iOS for push notifications.

**What alternatives did you consider?**
None

**Additional Context**
PagerDuty provides two custom sounds for push notifications.  One for low priority and one for high priority incidents.

**Comment by madhudskumar** [comment]
fixed in v2.7.31 of app
