### ISSUE TITLE
ElastAlert alert source integration

### ISSUE THREAD

**Issue by raghuchinnannan** [squadcastHQ/squadcast-support#7]
**Is your feature request related to a problem you are facing? Please describe.**
Squadcast has an ELK alert source integration using Watcher. However, this is a paid feature and users who are using the free open source version can't use this without a Subscription and they rely on ElastAlert, an open source alternative by Yelp.

**Describe the ideal solution that could solve this problem for you**
The Ideal solution would be an alert source integration with ElastAlert like Squadcast already has with Elastic watcher.

**What alternatives did you consider?**
Can try using custom scripts to create incidents using Squadcast API alert source integration.

**Additional Context**
Elastic watcher alertsource integration by Squadcast - https://support.squadcast.com/docs/elastic
ElastAlert - https://github.com/Yelp/elastalert/

**Comment by sisirkoppaka** [comment]
Let's revisit this once we have published a way for users and partnerns to add and modify such integrations.

cc @botsie @raghuchinnannan

**Comment by raghuchinnannan** [comment]
This integration has been completed.
https://support.squadcast.com/docs/elastalert
